//
//  TvSerialPresenter.swift
//  MoviesApp
//
//  Created by Sergey Stelmakh on 04.02.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Логика презентации
protocol TvSerialPresentationLogic {
  
}

/// Протокол для работы TvSerialPresenter из TvSerialViewController
protocol TvSerialViewControllerOutput {
    
}

/// Презентер VIPER-модуля детальной информации сериала
final class TvSerialPresenter {
    weak var viewController: TvSerialDisplayLogic?
    var interactor: TvSerialBusinessLogic?
    var router: TvSerialRoutingLogic?
}

// MARK: - TvSerialViewControllerOutput
extension TvSerialPresenter: TvSerialViewControllerOutput {
    
}

// MARK: - TvSerialPresentationLogic
extension TvSerialPresenter: TvSerialPresentationLogic {
    
}

