//
//  FavoritesInteractor.swift
//  MoviesApp
//
//  Created by Sergey Stelmakh on 14.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoritesBusinessLogic {
}

final class FavoritesInteractor {
    var presenter: FavoritesPresentationLogic?
}

// MARK: - FavoritesBusinessLogic
extension FavoritesInteractor: FavoritesBusinessLogic {
    
}
