//
//  MoviesPresenter.swift
//  MoviesApp
//
//  Created by Sergey Stelmakh on 09.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Логика презентации
protocol MoviesPresentationLogic {
    /// Ошибка от сервера
    /// - Parameter text: Текст ошибки
    func showErrorMessage(text: String)
    
    func loadDataSuccess(trends: [Trend], tvPopulars: [TvPopular])
}

/// Протокол для работы MoviesPresenter из MoviesViewController
protocol MoviesViewControllerOutput {
    /// Загрузка данных
    func loadData()
}

/// Презентер VIPER-модуля Фильмов
final class MoviesPresenter {
    weak var viewController: MoviesDisplayLogic?
    var interactor: MoviesBusinessLogic?
    var router: MoviesRoutingLogic?
}

// MARK: - MoviesPresentationLogic
extension MoviesPresenter: MoviesPresentationLogic {
    func loadDataSuccess(trends: [Trend], tvPopulars: [TvPopular]) {
        viewController?.loadDataDone(trends: trends, tvPopulars: tvPopulars)
        
        DispatchQueue.main.async { [weak self] in
            self?.viewController?.reloadRows()
        }
    }
    
    func showErrorMessage(text: String) {
        
    }
}

// MARK: - MoviesViewControllerOutput
extension MoviesPresenter: MoviesViewControllerOutput {
    func loadData() {
        interactor?.retrieveData()
    }
}
