//
//  MoviesPresenter.swift
//  MoviesApp
//
//  Created by Sergey Stelmakh on 09.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Логика презентации
protocol MoviesPresentationLogic {

}

/// Протокол для работы MoviesPresenter из MoviesViewController
protocol MoviesViewControllerOutput {
    
}

final class MoviesPresenter {
    weak var viewController: MoviesDisplayLogic?
    var interactor: MoviesBusinessLogic?
    var router: MoviesRoutingLogic?
}

// MARK: - MoviesPresentationLogic
extension MoviesPresenter: MoviesPresentationLogic {
    
}

// MARK: - MoviesViewControllerOutput
extension MoviesPresenter: MoviesViewControllerOutput {
    
}
