//
//  MovieViewController.swift
//  MoviesApp
//
//  Created by Sergey Stelmakh on 04.02.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Протокол отображения MovieViewController-а
protocol MovieDisplayLogic: AnyObject {
  
}

/// Детальный экран фильма
final class MovieViewController: UIViewController {
    
    var presenter: MovieViewControllerOutput?
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
}

// MARK: - MovieDisplayLogic
extension MovieViewController: MovieDisplayLogic {
    
}
