//
//  MoviePresenter.swift
//  MoviesApp
//
//  Created by Sergey Stelmakh on 04.02.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Логика презентации
protocol MoviePresentationLogic {
  
}

/// Протокол для работы MoviePresenter из MovieViewController
protocol MovieViewControllerOutput {
    
}

/// Презентер VIPER-модуля детальной информации фильма
final class MoviePresenter {
    weak var viewController: MovieDisplayLogic?
    var interactor: MovieBusinessLogic?
    var router: MovieRoutingLogic?
}

// MARK: - MovieViewControllerOutput
extension MoviePresenter: MovieViewControllerOutput {
    
}

// MARK: - MoviePresentationLogic
extension MoviePresenter: MoviePresentationLogic {
    
}
