//
//  ProfilePresenter.swift
//  MoviesApp
//
//  Created by Sergey Stelmakh on 04.07.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfilePresentationLogic {
    
}

protocol ProfileViewControllerOutput {
    
}

final class ProfilePresenter {
  weak var viewController: ProfileDisplayLogic?
    var interactor: ProfileBusinessLogic?
    var router: ProfileRoutingLogic?
}

extension ProfilePresenter: ProfilePresentationLogic {
    
}

extension ProfilePresenter: ProfileViewControllerOutput {
    
}
