//
//  SearchSettingsPresenter.swift
//  MoviesApp
//
//  Created by Sergey Stelmakh on 31.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchSettingsPresentationLogic {
  
}

/// Протокол для работы SearchSettingsPresenter из SearchSettingsViewController
protocol SearchSettingsViewControllerOutput {
    func setAdultFilter(_ isOn: Bool)
    func getAdultFilter() -> Bool
}

final class SearchSettingsPresenter {
    weak var viewController: SearchSettingsDisplayLogic?
    var interactor: SearchSettingsBusinessLogic?
    var router: SearchSettingsRoutingLogic?
}

extension SearchSettingsPresenter: SearchSettingsPresentationLogic {
    
}

extension SearchSettingsPresenter: SearchSettingsViewControllerOutput {
    func setAdultFilter(_ isOn: Bool) {
        interactor?.setAdultFilter(isOn)
    }
    
    func getAdultFilter() -> Bool {
        return interactor?.getAdultFilter() ?? false
    }
}
