//
//  SearchSettingsInteractor.swift
//  MoviesApp
//
//  Created by Sergey Stelmakh on 31.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchSettingsBusinessLogic {
    func setAdultFilter(_ isOn: Bool)
    func getAdultFilter() -> Bool
}

final class SearchSettingsInteractor {
    var presenter: SearchSettingsPresentationLogic?
    static let adultFilterValue = "adultFilterValue"
    private let defaults = UserDefaults.standard
}

// MARK: - SearchSettingsBusinessLogic
extension SearchSettingsInteractor: SearchSettingsBusinessLogic {
    func setAdultFilter(_ isOn: Bool) {
        defaults.set(isOn, forKey: SearchSettingsInteractor.adultFilterValue)
    }
    
    func getAdultFilter() -> Bool {
        return defaults.bool(forKey: SearchSettingsInteractor.adultFilterValue)
    }
}
