//
//  SearchInteractor.swift
//  MoviesApp
//
//  Created by Sergey Stelmakh on 14.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchBusinessLogic {
    /// Получаем данные
    /// - Parameter query: запрос
    func retrieveSearchMovie(query: String)
}


final class SearchInteractor {
    var presenter: SearchPresentationLogic?
    private let defaults = UserDefaults.standard
    private var service: NetworkServiceProtocol = APIRequest.shared
}

// MARK: - SearchBusinessLogic
extension SearchInteractor: SearchBusinessLogic {
    func retrieveSearchMovie(query: String) {
        let includeAdult = defaults.bool(forKey: SearchSettingsInteractor.adultFilterValue)
        service.searchMovie(query: query, includeAdult: includeAdult) { [weak self] response in
            switch response {
            case .success(let data):
                self?.presenter?.searchMovieSuccess(movies: data.results)
            case .failure(let error):
                _ = error
                self?.presenter?.searchMovieFailure()
            }
        }
    }
}
