//
//  SearchPresenter.swift
//  MoviesApp
//
//  Created by Sergey Stelmakh on 14.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Логика презентации
protocol SearchPresentationLogic {
  
}

/// Протокол для работы SearchPresenter из SearchViewController
protocol SearchViewControllerOutput {
    func presentSettingsScreen(view: UIViewController)
}

/// Презентер VIPER-модуля поиска
final class SearchPresenter {
    weak var viewController: SearchDisplayLogic?
    var interactor: SearchBusinessLogic?
    var router: SearchRoutingLogic?
}

// MARK: - SearchPresentationLogic
extension SearchPresenter: SearchPresentationLogic {
    
}

// MARK: - SearchViewControllerOutput
extension SearchPresenter: SearchViewControllerOutput {
    func presentSettingsScreen(view: UIViewController) {
        router?.presentSettingsScreen(from: view)
    }
}
