//
//  SearchViewController.swift
//  MoviesApp
//
//  Created by Sergey Stelmakh on 14.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Протокол отображения SearchViewController-а
protocol SearchDisplayLogic: AnyObject {
  
}

/// Экран поиска фильмов
final class SearchViewController: UIViewController {
  
    /// Ссылка на слой презентации
    var presenter: SearchViewControllerOutput?
    
    // MARK: View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        setup()
        setupConstraints()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
    }
}

// MARK: - Setup
private extension SearchViewController {
    func setup() {
        view.backgroundColor = .white
        title = "Поиск 🔎"
    }
}

// MARK: - Setup constraints
private extension SearchViewController {
    func setupConstraints() {
        
    }
}

extension SearchViewController: SearchDisplayLogic {
    
}
